/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DefinitionsmodelUserFormats from './DefinitionsmodelUserFormats';
import GinH from './GinH';

/**
* The AllOfinlineResponse2001Data model module.
* @module model/AllOfinlineResponse2001Data
* @version 1.0
*/
export default class AllOfinlineResponse2001Data {
    /**
    * Constructs a new <code>AllOfinlineResponse2001Data</code>.
    * @alias module:model/AllOfinlineResponse2001Data
    * @class
    * @extends module:model/GinH
    */

    constructor() {
        GinH.call(this);
        
        
    }

    /**
    * Constructs a <code>AllOfinlineResponse2001Data</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AllOfinlineResponse2001Data} obj Optional instance to populate.
    * @return {module:model/AllOfinlineResponse2001Data} The populated <code>AllOfinlineResponse2001Data</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllOfinlineResponse2001Data();
            
            GinH.constructFromObject(data, obj);
            
            if (data.hasOwnProperty('list')) {
                obj['list'] = ApiClient.convertToType(data['list'], [DefinitionsmodelUserFormats]);
            }
            if (data.hasOwnProperty('total')) {
                obj['total'] = ApiClient.convertToType(data['total'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/DefinitionsmodelUserFormats>} list
    */
    'list' = undefined;
    /**
    * @member {Number} total
    */
    'total' = undefined;




}
