/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The BindQueryUser model module.
* @module model/BindQueryUser
* @version 1.0
*/
export default class BindQueryUser {
    /**
    * Constructs a new <code>BindQueryUser</code>.
    * @alias module:model/BindQueryUser
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>BindQueryUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BindQueryUser} obj Optional instance to populate.
    * @return {module:model/BindQueryUser} The populated <code>BindQueryUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BindQueryUser();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('offset')) {
                obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {Number} limit
    */
    'limit' = undefined;
    /**
    * @member {Number} offset
    */
    'offset' = undefined;




}
