/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BindConfig from './BindConfig';

/**
* The BindBodyConfig model module.
* @module model/BindBodyConfig
* @version 1.0
*/
export default class BindBodyConfig extends Array {
    /**
    * Constructs a new <code>BindBodyConfig</code>.
    * @alias module:model/BindBodyConfig
    * @class
    * @extends Array
    */

    constructor() {
        super();
        
        
        return this;
    }

    /**
    * Constructs a <code>BindBodyConfig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BindBodyConfig} obj Optional instance to populate.
    * @return {module:model/BindBodyConfig} The populated <code>BindBodyConfig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BindBodyConfig();
            ApiClient.constructFromObject(data, obj, 'BindConfig');
            
            
        }
        return obj;
    }





}
