/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The BindBodyUserPatch model module.
* @module model/BindBodyUserPatch
* @version 1.0
*/
export default class BindBodyUserPatch {
    /**
    * Constructs a new <code>BindBodyUserPatch</code>.
    * @alias module:model/BindBodyUserPatch
    * @class
    * @param token {String} 
    */

    constructor(token) {
        
        
        this['token'] = token;
        
    }

    /**
    * Constructs a <code>BindBodyUserPatch</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BindBodyUserPatch} obj Optional instance to populate.
    * @return {module:model/BindBodyUserPatch} The populated <code>BindBodyUserPatch</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BindBodyUserPatch();
                        
            
            if (data.hasOwnProperty('activated')) {
                obj['activated'] = ApiClient.convertToType(data['activated'], 'Boolean');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} activated
    */
    'activated' = undefined;
    /**
    * @member {String} password
    */
    'password' = undefined;
    /**
    * @member {String} token
    */
    'token' = undefined;




}
