/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The BindBodyUser model module.
* @module model/BindBodyUser
* @version 1.0
*/
export default class BindBodyUser {
    /**
    * Constructs a new <code>BindBodyUser</code>.
    * @alias module:model/BindBodyUser
    * @class
    * @param email {String} 
    * @param password {String} 
    */

    constructor(email, password) {
        
        
        this['email'] = email;
        this['password'] = password;
        
    }

    /**
    * Constructs a <code>BindBodyUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BindBodyUser} obj Optional instance to populate.
    * @return {module:model/BindBodyUser} The populated <code>BindBodyUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BindBodyUser();
                        
            
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('ticket')) {
                obj['ticket'] = ApiClient.convertToType(data['ticket'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {String} password
    */
    'password' = undefined;
    /**
    * @member {String} ticket
    */
    'ticket' = undefined;




}
