/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The BindConfig model module.
* @module model/BindConfig
* @version 1.0
*/
export default class BindConfig {
    /**
    * Constructs a new <code>BindConfig</code>.
    * @alias module:model/BindConfig
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>BindConfig</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BindConfig} obj Optional instance to populate.
    * @return {module:model/BindConfig} The populated <code>BindConfig</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BindConfig();
                        
            
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} key
    */
    'key' = undefined;
    /**
    * @member {String} value
    */
    'value' = undefined;




}
