/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The GinH model module.
* @module model/GinH
* @version 1.0
*/
export default class GinH {
    /**
    * Constructs a new <code>GinH</code>.
    * @alias module:model/GinH
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>GinH</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GinH} obj Optional instance to populate.
    * @return {module:model/GinH} The populated <code>GinH</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GinH();
                        
            
        }
        return obj;
    }





}
