/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The HttputilJSONResponse model module.
* @module model/HttputilJSONResponse
* @version 1.0
*/
export default class HttputilJSONResponse {
    /**
    * Constructs a new <code>HttputilJSONResponse</code>.
    * @alias module:model/HttputilJSONResponse
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>HttputilJSONResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HttputilJSONResponse} obj Optional instance to populate.
    * @return {module:model/HttputilJSONResponse} The populated <code>HttputilJSONResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HttputilJSONResponse();
                        
            
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], Object);
            }
            if (data.hasOwnProperty('msg')) {
                obj['msg'] = ApiClient.convertToType(data['msg'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} code
    */
    'code' = undefined;
    /**
    * @member {Object} data
    */
    'data' = undefined;
    /**
    * @member {String} msg
    */
    'msg' = undefined;




}
