/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HttputilJSONResponse from './HttputilJSONResponse';
import ModelUserProfile from './ModelUserProfile';

/**
* The InlineResponse200 model module.
* @module model/InlineResponse200
* @version 1.0
*/
export default class InlineResponse200 {
    /**
    * Constructs a new <code>InlineResponse200</code>.
    * @alias module:model/InlineResponse200
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse200} obj Optional instance to populate.
    * @return {module:model/InlineResponse200} The populated <code>InlineResponse200</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200();
                        
            
            if (data.hasOwnProperty('data')) {
                obj['data'] = ModelUserProfile.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('httputil.JSONResponse')) {
                obj['httputil.JSONResponse'] = HttputilJSONResponse.constructFromObject(data['httputil.JSONResponse']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ModelUserProfile} data
    */
    'data' = undefined;
    /**
    * @member {module:model/HttputilJSONResponse} httputil.JSONResponse
    */
    'httputil.JSONResponse' = undefined;




}
