/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The ModelUser model module.
* @module model/ModelUser
* @version 1.0
*/
export default class ModelUser {
    /**
    * Constructs a new <code>ModelUser</code>.
    * @alias module:model/ModelUser
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>ModelUser</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModelUser} obj Optional instance to populate.
    * @return {module:model/ModelUser} The populated <code>ModelUser</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelUser();
                        
            
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('ticket')) {
                obj['ticket'] = ApiClient.convertToType(data['ticket'], 'String');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('ux')) {
                obj['ux'] = ApiClient.convertToType(data['ux'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} created
    */
    'created' = undefined;
    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {String} role
    */
    'role' = undefined;
    /**
    * @member {String} status
    */
    'status' = undefined;
    /**
    * @member {String} ticket
    */
    'ticket' = undefined;
    /**
    * @member {String} updated
    */
    'updated' = undefined;
    /**
    * @member {String} username
    */
    'username' = undefined;
    /**
    * Global unique user ID
    * @member {String} ux
    */
    'ux' = undefined;




}
