/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import HttputilJSONResponse from '../model/HttputilJSONResponse';

/**
* Configs service.
* @module api/ConfigsApi
* @version 1.0
*/
export default class ConfigsApi {

    /**
    * Constructs a new ConfigsApi. 
    * @alias module:api/ConfigsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the configsKeyDelete operation.
     * @callback module:api/ConfigsApi~configsKeyDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HttputilJSONResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 删除配置项
     * 根据键名删除配置项
     * @param {module:api/ConfigsApi~configsKeyDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HttputilJSONResponse}
     */
    configsKeyDelete(key, callback) {
      let postBody = null;

      let pathParams = {
        'key': key
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HttputilJSONResponse;

      return this.apiClient.callApi(
        '/configs/{key}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the configsKeyGet operation.
     * @callback module:api/ConfigsApi~configsKeyGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HttputilJSONResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 获取配置项
     * 根据键名获取配置项
     * @param {module:api/ConfigsApi~configsKeyGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HttputilJSONResponse}
     */
    configsKeyGet(key, callback) {
      let postBody = null;

      let pathParams = {
        'key': key
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HttputilJSONResponse;

      return this.apiClient.callApi(
        '/configs/{key}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the configsKeyPut operation.
     * @callback module:api/ConfigsApi~configsKeyPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HttputilJSONResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 修改配置项
     * 根据键名修改配置项
     * @param {module:api/ConfigsApi~configsKeyPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HttputilJSONResponse}
     */
    configsKeyPut(body, key, callback) {
      let postBody = body;

      let pathParams = {
        'key': key
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = HttputilJSONResponse;

      return this.apiClient.callApi(
        '/configs/{key}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
