/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import BindBodyToken from '../model/BindBodyToken';
import HttputilJSONResponse from '../model/HttputilJSONResponse';

/**
* Tokens service.
* @module api/TokensApi
* @version 1.0
*/
export default class TokensApi {

    /**
    * Constructs a new TokensApi. 
    * @alias module:api/TokensApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the tokensDelete operation.
     * @callback module:api/TokensApi~tokensDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HttputilJSONResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 退出登录
     * 用户状态登出
     * @param {module:api/TokensApi~tokensDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HttputilJSONResponse}
     */
    tokensDelete(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HttputilJSONResponse;

      return this.apiClient.callApi(
        '/tokens', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the tokensPost operation.
     * @callback module:api/TokensApi~tokensPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/HttputilJSONResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * 登录/密码重置
     * 用于账户登录和申请密码重置
     * @param {module:api/TokensApi~tokensPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/HttputilJSONResponse}
     */
    tokensPost(body, callback) {
      let postBody = body;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = HttputilJSONResponse;

      return this.apiClient.callApi(
        '/tokens', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
