/**
 * Moreu API
 * This is a moreu server.
 *
 * OpenAPI spec version: 1.0
 * Contact: saltbo@foxmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from './ApiClient';
import AllOfinlineResponse2001Data from './model/AllOfinlineResponse2001Data';
import BindBodyToken from './model/BindBodyToken';
import BindBodyUser from './model/BindBodyUser';
import BindBodyUserPatch from './model/BindBodyUserPatch';
import BindQueryUser from './model/BindQueryUser';
import GinH from './model/GinH';
import HttputilJSONResponse from './model/HttputilJSONResponse';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse2002 from './model/InlineResponse2002';
import ModelUser from './model/ModelUser';
import ModelUserFormats from './model/ModelUserFormats';
import ModelUserProfile from './model/ModelUserProfile';
import ConfigsApi from './api/ConfigsApi';
import TokensApi from './api/TokensApi';
import UsersApi from './api/UsersApi';

/**
* This_is_a_moreu_server_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MoreuApi = require('index'); // See note below*.
* var xxxSvc = new MoreuApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MoreuApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MoreuApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MoreuApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AllOfinlineResponse2001Data model constructor.
     * @property {module:model/AllOfinlineResponse2001Data}
     */
    AllOfinlineResponse2001Data,

    /**
     * The BindBodyToken model constructor.
     * @property {module:model/BindBodyToken}
     */
    BindBodyToken,

    /**
     * The BindBodyUser model constructor.
     * @property {module:model/BindBodyUser}
     */
    BindBodyUser,

    /**
     * The BindBodyUserPatch model constructor.
     * @property {module:model/BindBodyUserPatch}
     */
    BindBodyUserPatch,

    /**
     * The BindQueryUser model constructor.
     * @property {module:model/BindQueryUser}
     */
    BindQueryUser,

    /**
     * The GinH model constructor.
     * @property {module:model/GinH}
     */
    GinH,

    /**
     * The HttputilJSONResponse model constructor.
     * @property {module:model/HttputilJSONResponse}
     */
    HttputilJSONResponse,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The ModelUser model constructor.
     * @property {module:model/ModelUser}
     */
    ModelUser,

    /**
     * The ModelUserFormats model constructor.
     * @property {module:model/ModelUserFormats}
     */
    ModelUserFormats,

    /**
     * The ModelUserProfile model constructor.
     * @property {module:model/ModelUserProfile}
     */
    ModelUserProfile,

    /**
    * The ConfigsApi service constructor.
    * @property {module:api/ConfigsApi}
    */
    ConfigsApi,

    /**
    * The TokensApi service constructor.
    * @property {module:api/TokensApi}
    */
    TokensApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
